# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Learning_RxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Learning_RxSwift
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
end
